book_genres = [
    "Adventure",
    "Autobiography",
    "Biography",
    "Chick Lit",
    "Children's",
    "Classic",
    "Comic/Graphic Novel",
    "Contemporary",
    "Crime",
    "Drama",
    "Dystopian",
    "Erotica",
    "Espionage",
    "Fantasy",
    "Gothic",
    "Historical Fiction",
    "Horror",
    "Humor",
    "Inspirational",
    "Literary Fiction",
    "Memoir",
    "Mystery",
    "Mythology",
    "Non-Fiction",
    "Paranormal",
    "Philosophical",
    "Poetry",
    "Political",
    "Post-Apocalyptic",
    "Religious",
    "Romance",
    "Satire",
    "Science Fiction",
    "Self-Help",
    "Short Story Collection",
    "Suspense",
    "Thriller",
    "Travel",
    "True Crime",
    "Urban Fiction",
    "War",
    "Western",
    "Young Adult (YA)",
    "Historical Romance",
    "Psychological Thriller",
    "Fairy Tale",
    "Alternate History",
    "Magical Realism",
    "Steampunk",
    "Cyberpunk"
]
genders = [
    'Male', 'Female', 'LGBTQ+'
]
occupations = [
    "Passed away",
    "Unemployed", 
    "Accountant",
    "Actor",
    "Aerospace Engineer",
    "Agricultural Engineer",
    "Air Traffic Controller",
    "Anthropologist",
    "Architect",
    "Artist",
    "Astronaut",
    "Astronomer",
    "Athlete",
    "Audiologist",
    "Author",
    "Baker",
    "Banker",
    "Barber",
    "Bartender",
    "Biologist",
    "Blacksmith",
    "Botanist",
    "Bricklayer",
    "Broker",
    "Bus Driver",
    "Butcher",
    "Carpenter",
    "Cartographer",
    "Chef",
    "Chemist",
    "Chiropractor",
    "Civil Engineer",
    "Clinical Psychologist",
    "Computer Programmer",
    "Conservationist",
    "Construction Worker",
    "Consultant",
    "Counselor",
    "Dancer",
    "Dentist",
    "Dermatologist",
    "Dietitian",
    "DJ (Disc Jockey)",
    "Doctor",
    "Economist",
    "Editor",
    "Electrician",
    "Elementary School Teacher",
    "Emergency Medical Technician",
    "Environmental Scientist",
    "Event Planner",
    "Farmer",
    "Fashion Designer",
    "Film Director",
    "Financial Advisor",
    "Firefighter",
    "Fisherman",
    "Flight Attendant",
    "Florist",
    "Forensic Scientist",
    "Game Developer",
    "Graphic Designer",
    "Hairdresser",
    "Historian",
    "Hotel Manager",
    "Interior Designer",
    "Investigative Journalist",
    "Judge",
    "Lawyer",
    "Librarian",
    "Lifeguard",
    "Locksmith",
    "Makeup Artist",
    "Marine Biologist",
    "Mason",
    "Massage Therapist",
    "Mathematician",
    "Mechanic",
    "Meteorologist",
    "Midwife",
    "Military Officer",
    "Miner",
    "Musician",
    "Nurse",
    "Nutritionist",
    "Obstetrician",
    "Occupational Therapist",
    "Oceanographer",
    "Optometrist",
    "Painter",
    "Paramedic",
    "Pastry Chef",
    "Pediatrician",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Physicist",
    "Pilot",
    "Plumber",
    "Podiatrist",
    "Police Officer",
    "Politician",
    "Professor",
    "Psychiatrist",
    "Radiologist",
    "Real Estate Agent",
    "Registered Nurse",
    "Reporter",
    "Research Scientist",
    "Restaurant Manager",
    "Roofer",
    "Sociologist",
    "Software Engineer",
    "Surgeon",
    "Tailor",
    "Taxi Driver",
    "Teacher",
    "Translator",
    "Travel Agent",
    "Veterinarian",
    "Videographer",
    "Waiter/Waitress",
    "Web Developer",
    "Welder",
    "Writer",
    "Zoologist"
]
culturally_diverse_cities = [
    "New York City, USA",
    "Toronto, Canada",
    "London, UK",
    "Sydney, Australia",
    "Mumbai, India",
    "Rio de Janeiro, Brazil",
    "Johannesburg, South Africa",
    "Shanghai, China",
    "Dubai, UAE",
    "Paris, France",
    "Los Angeles, USA",
    "Singapore, Singapore",
    "Tokyo, Japan",
    "Mexico City, Mexico",
    "Cairo, Egypt",
    "Istanbul, Turkey",
    "Lagos, Nigeria",
    "Berlin, Germany",
    "Bangkok, Thailand",
    "Kuala Lumpur, Malaysia",
    "Nairobi, Kenya",
    "São Paulo, Brazil",
    "Buenos Aires, Argentina",
    "Jakarta, Indonesia",
    "Manila, Philippines",
    "Lima, Peru",
    "Moscow, Russia",
    "Tehran, Iran",
    "Auckland, New Zealand",
    "Miami, USA",
    "Hong Kong, China",
    "Seoul, South Korea",
    "Cape Town, South Africa",
    "Melbourne, Australia",
    "Barcelona, Spain",
    "Marrakesh, Morocco",
    "Casablanca, Morocco",
    "Beijing, China",
    "Rome, Italy",
    "Amsterdam, Netherlands",
    "Bogotá, Colombia",
    "Hanoi, Vietnam",
    "Ho Chi Minh City, Vietnam",
    "Dhaka, Bangladesh",
    "Karachi, Pakistan",
    "Montreal, Canada",
    "San Francisco, USA",
    "Madrid, Spain",
    "Tel Aviv, Israel",
    "Prague, Czech Republic",
    "Budapest, Hungary",
    "Warsaw, Poland",
    "Lisbon, Portugal",
    "Kiev, Ukraine",
    "Santiago, Chile",
    "Athens, Greece",
    "Kingston, Jamaica",
    "Havana, Cuba",
    "San Jose, Costa Rica",
    "Panama City, Panama",
    "Addis Ababa, Ethiopia",
    "Accra, Ghana",
    "Dar es Salaam, Tanzania",
    "Algiers, Algeria",
    "Tunis, Tunisia",
    "Harare, Zimbabwe",
    "Antananarivo, Madagascar",
    "Oslo, Norway",
    "Stockholm, Sweden",
    "Helsinki, Finland",
    "Copenhagen, Denmark",
    "Dublin, Ireland",
    "Brussels, Belgium",
    "Zurich, Switzerland",
    "Vienna, Austria",
    "Sarajevo, Bosnia and Herzegovina",
    "Belgrade, Serbia",
    "Skopje, North Macedonia",
    "Tbilisi, Georgia",
    "Yerevan, Armenia",
    "Baku, Azerbaijan",
    "Astana, Kazakhstan",
    "Ulaanbaatar, Mongolia",
    "Taipei, Taiwan",
    "Manama, Bahrain",
    "Amman, Jordan",
    "Riyadh, Saudi Arabia",
    "Doha, Qatar",
    "Kuwait City, Kuwait",
    "Muscat, Oman",
    "Baghdad, Iraq",
    "Beirut, Lebanon",
    "Abidjan, Côte d'Ivoire",
    "Dakar, Senegal",
    "Port-au-Prince, Haiti"
]